config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#root'

  get '/auth/:provider/callback', to: 'api/sessions#omniauth', defaults: { format: :json }

  namespace :api, defaults: { format: :json } do

    get 'search', to: 'trends#search'

    get 'trends/stories', to: 'trends#stories'

    get 'trends/authors', to: 'trends#authors'

    resource :session, only: [:create, :destroy]

    get 'profile', to: 'users#profile'

    resources :tags, only: :show

    resources :tags, only: [:index, :create] do
      resources :stories
    end

    resource :feed, only: :show
    
    resource :follow, only: [:create, :destroy]

    resources :users, only: [:show] do
      resources :stories, only: :index
    end

    resource :user, only: :update
    resources :users, only: :create

    resources :comments, only: [:create]

    resources :stories, only: [:index, :show, :create, :update, :destroy] do
      resources :comments, only: [:index]
    end

  end

end

app/views/pages/_sidebar.html.erb
<div id="sidebar" class="clearfix">
  <nav class="sidebar-nav">
    <input type="text" value="Search">
    <a href="#" id="current-user" data-id="<%= current_user.id %>">
      Home
    </a>
    <%= button_to "Log out", session_url(current_session), method: :delete %>
    <a href="#stories/new">New story</a>
  </nav>
</div>

app/views/pages/root.html.erb
<div id="sidebar" class="sidebar slide-out clearfix">
</div>

<main class="sidebar-offset" id="app"></main>

<div class="loading-modal"></div>

<script type="text/javascript">
  $(document).ready(function(){
    MediumClone.initialize();
  });
</script>